# Generated by Django 4.2.7 on 2025-08-24 09:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_about_photo_alter_personal_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
